### ISSUE TITLE
Not able to create a node with event_attributes

### ISSUE THREAD

**Issue by knowtheunknown** [PaloAltoNetworks/minemeld-misp#6]
Hi all!
When I create a node assigned to a prototype that it use event_attributes, engine go into a fatal status when I try to compile it. Is it possible to add just a single event_attribute? Am I doing something wrong?

```
age_out:
    default: null
    sudden_death: true
attributes:
    confidence: 70
    share_leve: white
client_cert_required: false
event_attributes:
    uuid: XXXXXXX-XXXX-XXXX-XXXX-XXXXXXX
filters:
    published: 1
    tag: tlp:white
honour_ids_flag: true
indicator_types: IPv4
source_name: misp.name
url: https://<misp.url>
verify_cert: true
```

Thank's!
